version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200" 
    volumes:
      - .:/app 
      - /app/node_modules 
    stdin_open: true
    tty: true
